language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

policies:
  - epochs: 50
    max_history: 6
    name: KerasPolicy
  - core_threshold: 0.3
    name: FallbackPolicy
    nlu_threshold: 0.8