language: en

language: "en"

pipeline: "pretrained_embeddings_spacy"

policies:
  - epochs: 50
    max_history: 6
    name: KerasPolicy
  - core_threshold: 0.3
    name: FallbackPolicy
    nlu_threshold: 0.8