language: en

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"

policies:
  - name: "examples.restaurantbot.policy.RestaurantPolicy"
    batch_size: 100
    epochs: 100
    validation_split: 0.2
  - name: MemoizationPolicy
  - name: MappingPolicy
